spring:
  h2:
    console:
      enabled: false

app:
  security:
    h2-console-enabled: false
    prometheus-public-enabled: false
    frame-options: deny
    cors:
      allowed-origins: ${APP_SECURITY_CORS_ALLOWED_ORIGINS:}

jwt:
  secret: ${JWT_SECRET}

management:
  endpoint:
    health:
      show-details: never
