package com.mamoji.people.domain;

import java.math.BigDecimal;
import java.util.List;

/** Company-scoped employee record owned by People Core. */
public class Employee {
    public long id;
    public long companyId;
    public Long userId;
    public Long departmentId;
    public String departmentName;
    public String employeeNo;
    public String name;
    public String legalName;
    public String preferredName;
    public String email;
    public String phone;
    public String position;
    public Long directManagerEmployeeId;
    public String jobLevel;
    public String workLocation;
    public String employmentType;
    public String status;
    public String accessRole;
    public String accessScope;
    public String hireDate;
    public String leaveDate;
    public String probationStartDate;
    public String probationEndDate;
    public String contractStartDate;
    public String contractEndDate;
    public String contractType;
    public String contractStatus;
    public String educationLevel;
    public String graduationSchool;
    public String major;
    public String graduationDate;
    public Integer graduationYear;
    public String graduateStatus;
    public String skillTags;
    public String resumeSummary;
    public String materialStatus;
    public String profileVerifiedAt;
    public Long profileVerifiedBy;
    public BigDecimal salary;
    public BigDecimal overtimeBase;
    public BigDecimal weekdayOvertimeHours;
    public BigDecimal restDayOvertimeHours;
    public BigDecimal holidayOvertimeHours;
    public BigDecimal overtimePay;
    public String overtimePolicyNote;
    public BigDecimal socialInsurance;
    public BigDecimal housingFund;
    public BigDecimal taxEstimate;
    public BigDecimal monthlyCost;
    public BigDecimal socialInsuranceBase;
    public BigDecimal socialInsurancePersonalRate;
    public BigDecimal socialInsuranceCompanyRate;
    public BigDecimal socialInsurancePersonalAmount;
    public BigDecimal socialInsuranceCompanyAmount;
    public BigDecimal housingFundBase;
    public BigDecimal housingFundPersonalRate;
    public BigDecimal housingFundCompanyRate;
    public BigDecimal housingFundPersonalAmount;
    public BigDecimal housingFundCompanyAmount;
    public BigDecimal personalDeduction;
    public BigDecimal netPayEstimate;
    public String socialInsuranceRegion;
    public String hukouType;
    public String medicalTier;
    public BigDecimal pensionBase;
    public BigDecimal medicalBase;
    public BigDecimal unemploymentBase;
    public BigDecimal workInjuryBase;
    public BigDecimal maternityBase;
    public BigDecimal workInjuryCompanyRate;
    public String socialInsurancePolicyNote;
    public List<SocialInsuranceItem> socialInsuranceItems;
    public List<String> socialInsuranceWarnings;
    public List<EmployeeCertificate> certificates;
    public List<EmployeeExperience> experiences;
    public String emergencyContact;
    public String createdAt;
    public String updatedAt;
}
